export enum ActionDropdown {
    ACTIVE = 'COMMON.ACTIVE',
    INACTIVE = 'COMMON.INACTIVE',
    PUBLISH = 'COMMON.PUBLISH',
    UNPUBLISH = 'COMMON.UNPUBLISH',
    AFFECTED = 'COMMON.AFFECTED',
    DELETE = 'COMMON.DELETE',
}
